package com.ddf.fakeplayer.item;

import com.ddf.fakeplayer.item.items.TridentItem;
import com.ddf.fakeplayer.util.NotImplemented;

public class VanillaItems {
    public static Item mShovel_iron;
    public static Item mPickAxe_iron;
    public static Item mHatchet_iron;
    public static Item mFlintAndSteel;
    public static Item mApple;
    public static Item mBow;
    public static Item mCrossbow;
    public static Item mArrow;
    public static Item mCoal;
    public static Item mDiamond;
    public static Item mIronIngot;
    public static Item mGoldIngot;
    public static Item mSword_iron;
    public static Item mSword_wood;
    public static Item mShovel_wood;
    public static Item mPickAxe_wood;
    public static Item mHatchet_wood;
    public static Item mSword_stone;
    public static Item mShovel_stone;
    public static Item mPickAxe_stone;
    public static Item mHatchet_stone;
    public static Item mSword_diamond;
    public static Item mShovel_diamond;
    public static Item mPickAxe_diamond;
    public static Item mHatchet_diamond;
    public static Item mStick;
    public static Item mBowl;
    public static Item mMushroomStew;
    public static Item mSword_gold;
    public static Item mShovel_gold;
    public static Item mPickAxe_gold;
    public static Item mHatchet_gold;
    public static Item mString;
    public static Item mFeather;
    public static Item mSulphur;
    public static Item mHoe_wood;
    public static Item mHoe_stone;
    public static Item mHoe_iron;
    public static Item mHoe_diamond;
    public static Item mHoe_gold;
    public static Item mSeeds_wheat;
    public static Item mWheat;
    public static Item mBread;
    public static Item mHelmet_leather;
    public static Item mChestplate_leather;
    public static Item mLeggings_leather;
    public static Item mBoots_leather;
    public static Item mElytra;
    public static Item mHelmet_chain;
    public static Item mChestplate_chain;
    public static Item mLeggings_chain;
    public static Item mBoots_chain;
    public static Item mHelmet_iron;
    public static Item mChestplate_iron;
    public static Item mLeggings_iron;
    public static Item mBoots_iron;
    public static Item mHelmet_diamond;
    public static Item mChestplate_diamond;
    public static Item mLeggings_diamond;
    public static Item mBoots_diamond;
    public static Item mHelmet_gold;
    public static Item mChestplate_gold;
    public static Item mLeggings_gold;
    public static Item mBoots_gold;
    public static Item mShield;
    public static Item mFlint;
    public static Item mPorkChop_raw;
    public static Item mPorkChop_cooked;
    public static Item mPainting;
    public static Item mChorusFruit;
    public static Item mChorusFruitPopped;
    public static Item mApple_gold;
    public static Item mApple_enchanted;
    public static Item mSign;
    public static Item mDoor_wood;
    public static Item mBucket;
    public static Item mMinecart;
    public static Item mSaddle;
    public static Item mDoor_iron;
    public static Item mRedStone;
    public static Item mSnowBall;
    public static Item mBoat;
    public static Item mMobPlacer;
    public static Item mExperiencePotionItem;
    public static Item mFireCharge;
    public static Item mWritable_book;
    public static Item mWritten_book;
    public static Item mPumpkinPie;
    public static Item mLeatherHorseArmor;
    public static Item mIronHorseArmor;
    public static Item mGoldHorseArmor;
    public static Item mDiamondHorseArmor;
    public static Item mLead;
    public static Item mLeather;
    public static Item mRabbitHide;
    public static Item mBrick;
    public static Item mClay;
    public static Item mReeds;
    public static Item mKelp;
    public static Item mKelp_dried;
    public static Item mPaper;
    public static Item mBook;
    public static Item mSlimeBall;
    public static Item mChestMinecart;
    public static Item mEgg;
    public static Item mCompass;
    public static Item mFishingRod;
    public static Item mClock;
    public static Item mYellowDust;
    public static Item mCarrotOnAStick;
    public static Item mFish_raw_cod;
    public static Item mFish_raw_salmon;
    public static Item mFish_raw_clownfish;
    public static Item mFish_raw_pufferfish;
    public static Item mFish_cooked_cod;
    public static Item mFish_cooked_salmon;
    public static Item mMelonSlice;
    public static Item mSpeckled_melon;
    public static Item mSeeds_pumpkin;
    public static Item mSeeds_melon;
    public static Item mDye_powder;
    public static Item mBone;
    public static Item mSugar;
    public static Item mCake;
    public static Item mBed;
    public static Item mRepeater;
    public static Item mCookie;
    public static Item mPotato;
    public static Item mPotatoBaked;
    public static Item mCarrot;
    public static Item mGoldenCarrot;
    public static Item mBeetroot;
    public static Item mSeeds_beetroot;
    public static Item mBeetrootSoup;
    public static Item mSweetBerries;
    public static Item mSpider_eye;
    public static Item mFermented_spider_eye;
    public static Item mPoisonous_potato;
    public static Item mSkull;
    public static Item mEnderpearl;
    public static Item mEnderEye;
    public static Item mEndCrystal;
    public static Item mBlazeRod;
    public static Item mNether_wart;
    public static Item mGold_nugget;
    public static Item mIron_nugget;
    public static Item mBlazePowder;
    public static Item mNetherStar;
    public static Item mShears;
    public static Item mBeef_raw;
    public static Item mBeef_cooked;
    public static Item mChicken_raw;
    public static Item mChicken_cooked;
    public static Item mMutton_raw;
    public static Item mMutton_cooked;
    public static Item mRotten_flesh;
    public static Item mRabbitRaw;
    public static Item mRabbitCooked;
    public static Item mRabbitStew;
    public static Item mRabbitFoot;
    public static Item mArmorStand;
    public static Item mNameTag;
    public static Item mDoor_spruce;
    public static Item mDoor_birch;
    public static Item mDoor_jungle;
    public static Item mDoor_acacia;
    public static Item mDoor_darkoak;
    public static Item mGhast_tear;
    public static Item mMagma_cream;
    public static Item mBrewing_stand;
    public static Item mCauldron;
    public static Item mEnchanted_book;
    public static Item mComparator;
    public static Item mNetherbrick;
    public static Item mNetherQuartz;
    public static Item mTNTMinecart;
    public static Item mCommandBlockMinecart;
    public static Item mNautilusShell;
    public static Item mHeartOfTheSea;
    public static Item mPrismarineShard;
    public static Item mPrismarineCrystals;
    public static Item mEmerald;
    public static Item mItemFrame;
    public static Item mFlowerPot;
    public static Item mPotion;
    public static Item mSplash_potion;
    public static Item mLingering_potion;
    public static Item mGlass_bottle;
    public static Item mDragon_breath;
    public static Item mHopperMinecart;
    public static Item mHopper;
    public static Item mFilledMap;
    public static Item mEmptyMap;
    public static Item mBanner;
    public static Item mFireworkCharge;
    public static Item mFireworksItem;
    public static Item mPortfolioBook;
    public static Item mChalkboard;
    public static Item mCamera;
    public static Item mCompound;
    public static Item mIceBomb;
    public static Item mBleach;
    public static Item mRapidFertilizer;
    public static Item mBalloon;
    public static Item mMedicine;
    public static Item mSparkler;
    public static Item mGlowStick;
    public static Item mShulkerShell;
    public static Item mTotem;
    public static Item mRecord13;
    public static Item mRecordCat;
    public static Item mRecordBlocks;
    public static Item mRecordChirp;
    public static Item mRecordFar;
    public static Item mRecordMall;
    public static Item mRecordMellohi;
    public static Item mRecordStal;
    public static Item mRecordStrad;
    public static Item mRecordWard;
    public static Item mRecord11;
    public static Item mRecordWait;
    public static Item mTrident;
    public static Item mScute;
    public static Item mTurtleHelmet;
    public static Item mPhantomMembrane;
    public static Item mSpruceSign;
    public static Item mBirchSign;
    public static Item mJungleSign;
    public static Item mAcaciaSign;
    public static Item mDarkOakSign;
    public static Item mBell;
    public static Item mCampfire;
    public static Item mBannerPattern;
    public static Item mSuspiciousStew;
    public static Item mHoneycomb;
    public static Item mHoneyBottle;

    @NotImplemented
    public static void initClientData() {
    }

    @NotImplemented
    public static void registerItems() {
        VanillaItems.mApple = new Item("apple");
        ItemRegistry.registerItem(VanillaItems.mApple);
        VanillaItems.mApple_gold = new Item("golden_apple");
        ItemRegistry.registerItem(VanillaItems.mApple_gold);
        VanillaItems.mApple_enchanted = new Item("appleEnchanted");
        ItemRegistry.registerItem(VanillaItems.mApple_enchanted);
        VanillaItems.mMushroomStew = new Item("mushroom_stew");
        ItemRegistry.registerItem(VanillaItems.mMushroomStew);
        VanillaItems.mBread = new Item("bread");
        ItemRegistry.registerItem(VanillaItems.mBread);
        VanillaItems.mPorkChop_raw = new Item("porkchop");
        ItemRegistry.registerItem(VanillaItems.mPorkChop_raw);
        VanillaItems.mPorkChop_cooked = new Item("cooked_porkchop" );
        ItemRegistry.registerItem(VanillaItems.mPorkChop_cooked);
        VanillaItems.mFish_raw_cod = new Item("fish");
        ItemRegistry.registerItem(VanillaItems.mFish_raw_cod);
        VanillaItems.mFish_raw_salmon = new Item("salmon");
        ItemRegistry.registerItem(VanillaItems.mFish_raw_salmon);
        VanillaItems.mFish_raw_clownfish = new Item("clownfish");
        ItemRegistry.registerItem(VanillaItems.mFish_raw_clownfish);
        VanillaItems.mFish_raw_pufferfish = new Item("pufferfish");
        ItemRegistry.registerItem(VanillaItems.mFish_raw_pufferfish);
        VanillaItems.mFish_cooked_cod = new Item("cooked_fish");
        ItemRegistry.registerItem(VanillaItems.mFish_cooked_cod);
        VanillaItems.mFish_cooked_salmon = new Item("cooked_salmon");
        ItemRegistry.registerItem(VanillaItems.mFish_cooked_salmon);
        VanillaItems.mKelp_dried = new Item("dried_kelp");
        ItemRegistry.registerItem(VanillaItems.mKelp_dried);
        VanillaItems.mCookie = new Item("cookie");
        ItemRegistry.registerItem(VanillaItems.mCookie);
        VanillaItems.mMelonSlice = new Item("melon");
        ItemRegistry.registerItem(VanillaItems.mMelonSlice);
        VanillaItems.mBeef_raw = new Item("beef");
        ItemRegistry.registerItem(VanillaItems.mBeef_raw);
        VanillaItems.mBeef_cooked = new Item("cooked_beef");
        ItemRegistry.registerItem(VanillaItems.mBeef_cooked);
        VanillaItems.mChicken_raw = new Item("chicken");
        ItemRegistry.registerItem(VanillaItems.mChicken_raw);
        VanillaItems.mChicken_cooked = new Item("cooked_chicken");
        ItemRegistry.registerItem(VanillaItems.mChicken_cooked);
        VanillaItems.mRotten_flesh = new Item("rotten_flesh");
        ItemRegistry.registerItem(VanillaItems.mRotten_flesh);
        VanillaItems.mSpider_eye = new Item("spider_eye");
        ItemRegistry.registerItem(VanillaItems.mSpider_eye);
        VanillaItems.mCarrot = new Item("carrot");
        ItemRegistry.registerItem(VanillaItems.mCarrot);
        VanillaItems.mPotato = new Item("potato");
        ItemRegistry.registerItem(VanillaItems.mPotato);
        VanillaItems.mPotatoBaked = new Item("baked_potato");
        ItemRegistry.registerItem(VanillaItems.mPotatoBaked);
        VanillaItems.mPoisonous_potato = new Item("poisonous_potato");
        ItemRegistry.registerItem(VanillaItems.mPoisonous_potato);
        VanillaItems.mGoldenCarrot = new Item("golden_carrot");
        ItemRegistry.registerItem(VanillaItems.mGoldenCarrot);
        VanillaItems.mPumpkinPie = new Item("pumpkin_pie");
        ItemRegistry.registerItem(VanillaItems.mPumpkinPie);
        VanillaItems.mBeetroot = new Item("beetroot");
        ItemRegistry.registerItem(VanillaItems.mBeetroot);
        VanillaItems.mBeetrootSoup = new Item("beetroot_soup");
        ItemRegistry.registerItem(VanillaItems.mBeetrootSoup);
        VanillaItems.mSweetBerries = new Item("sweet_berries");
        ItemRegistry.registerItem(VanillaItems.mSweetBerries);
        VanillaItems.mRabbitRaw = new Item("rabbit");
        ItemRegistry.registerItem(VanillaItems.mRabbitRaw);
        VanillaItems.mRabbitCooked = new Item("cooked_rabbit");
        ItemRegistry.registerItem(VanillaItems.mRabbitCooked);
        VanillaItems.mRabbitStew = new Item("rabbit_stew");
        ItemRegistry.registerItem(VanillaItems.mRabbitStew);
        VanillaItems.mSeeds_wheat = new Item("wheat_seeds");
        ItemRegistry.registerItem(VanillaItems.mSeeds_wheat);
        VanillaItems.mSeeds_pumpkin = new Item("pumpkin_seeds");
        ItemRegistry.registerItem(VanillaItems.mSeeds_pumpkin);
        VanillaItems.mSeeds_melon = new Item("melon_seeds");
        ItemRegistry.registerItem(VanillaItems.mSeeds_melon);
        VanillaItems.mNether_wart = new Item("nether_wart");
        ItemRegistry.registerItem(VanillaItems.mNether_wart);
        VanillaItems.mSeeds_beetroot = new Item("beetroot_seeds");
        ItemRegistry.registerItem(VanillaItems.mSeeds_beetroot);

        VanillaItems.mTrident = new TridentItem("trident");
        ItemRegistry.registerItem(VanillaItems.mTrident);
        VanillaItems.mTrident.setMaxStackSize((byte) 1);
        VanillaItems.mTrident.setMaxDamage(250);

        //Alias
        ItemRegistry.registerAlias("minecraft:glazedTerracotta.purple", "minecraft:purple_glazed_terracotta");
        ItemRegistry.registerAlias("minecraft:glazedTerracotta.white", "minecraft:white_glazed_terracotta");
        ItemRegistry.registerAlias("minecraft:glazedTerracotta.orange", "minecraft:orange_glazed_terracotta");
        ItemRegistry.registerAlias("minecraft:glazedTerracotta.magenta", "minecraft:magenta_glazed_terracotta");
        ItemRegistry.registerAlias("minecraft:glazedTerracotta.light_blue", "minecraft:light_blue_glazed_terracotta");
        ItemRegistry.registerAlias("minecraft:glazedTerracotta.yellow", "minecraft:yellow_glazed_terracotta");
        ItemRegistry.registerAlias("minecraft:glazedTerracotta.lime", "minecraft:lime_glazed_terracotta");
        ItemRegistry.registerAlias("minecraft:glazedTerracotta.pink", "minecraft:pink_glazed_terracotta");
        ItemRegistry.registerAlias("minecraft:glazedTerracotta.gray", "minecraft:gray_glazed_terracotta");
        ItemRegistry.registerAlias("minecraft:glazedTerracotta.silver", "minecraft:silver_glazed_terracotta");
        ItemRegistry.registerAlias("minecraft:glazedTerracotta.cyan", "minecraft:cyan_glazed_terracotta");
        ItemRegistry.registerAlias("minecraft:glazedTerracotta.blue", "minecraft:blue_glazed_terracotta");
        ItemRegistry.registerAlias("minecraft:glazedTerracotta.brown", "minecraft:brown_glazed_terracotta");
        ItemRegistry.registerAlias("minecraft:glazedTerracotta.green", "minecraft:green_glazed_terracotta");
        ItemRegistry.registerAlias("minecraft:glazedTerracotta.red", "minecraft:red_glazed_terracotta");
        ItemRegistry.registerAlias("minecraft:glazedTerracotta.black", "minecraft:black_glazed_terracotta");
        ItemRegistry.registerAlias("minecraft:stone_slab", "minecraft:double_stone_slab");
        ItemRegistry.registerAlias("minecraft:stone_slab2", "minecraft:double_stone_slab2");
        ItemRegistry.registerAlias("minecraft:stone_slab3", "minecraft:double_stone_slab3");
        ItemRegistry.registerAlias("minecraft:stone_slab4", "minecraft:double_stone_slab4");
    }
}
